name: test (Run Tests)

on:
  pull_request:
    branches:
      - main


jobs:
  test:
      runs-on: ubunty-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: "22.x"

        - name: Setup dependencies
          run: npm install

        - name: Run tests
          run: npm test